/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RYZEN
 */
public class PanelAfiliados extends javax.swing.JPanel {
    
    DefaultTableModel modelo;
    private boolean btnVerActivo = false;
    private boolean btnEditarActivo = false;
    private boolean btnEliminarActivo = false;

    /**
     * Creates new form PanelDashboard
     */
    public PanelAfiliados() {
        initComponents();
        setSize(1086, 503);
        
        modelo = (DefaultTableModel) tablaAfiliados.getModel();

    }
    
    
    
    public void agregarDatosTabla(String[] datos){
        modelo.addRow(datos);
    }
    
    public void addTablaAfiliadosListener(MouseListener listener){
        tablaAfiliados.addMouseListener(listener);
    }
    
    public void addBtnVerListener(MouseListener listener){
        btnVer.addMouseListener(listener);
    }
    
    public void addBtnEditarListener(MouseListener listener){
        btnEditar.addMouseListener(listener);
    }
    
    public void addBtnEliminarListener(MouseListener listener){
        btnEliminar.addMouseListener(listener);
    }
    
    public void addBtnCrearListener(MouseListener listener){
        btnCrear.addMouseListener(listener);
    }
    
    public void activarBotones(){
        btnEditarActivo = true;
        btnEditarActivo = true;
        btnEliminarActivo = true;
        setBotonInactivo("Eliminar", btnEliminar);
        setBotonInactivo("Editar", btnEditar);
        setBotonInactivo("Ver", btnVer);     
    }
    
    private void setBotonActivo(String boton, JLabel imagenBoton){
        if(btnEditarActivo){
            Icon btnActivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Activo.png"); 
            imagenBoton.setIcon(btnActivo);
        }
        
        if("Crear".equals(boton)){
            Icon btnActivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Activo.png"); 
            imagenBoton.setIcon(btnActivo);
        }
        
        
    }
    
    private void setBotonInactivo(String boton, JLabel imagenBoton){
        if(btnEditarActivo){
            Icon btnInactivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Inactivo.png"); 
            imagenBoton.setIcon(btnInactivo);
        }
        
        if("Crear".equals(boton)){
            Icon btnInactivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Inactivo.png"); 
            imagenBoton.setIcon(btnInactivo);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAfiliados = new javax.swing.JTable();
        btnEliminar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        fondoAfiliados = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1086, 503));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonesCRUD/00-CrearInactivo.png"))); // NOI18N
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 144, 55));

        tablaAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Teléfono", "Correo", "Dirección", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAfiliados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaAfiliados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaAfiliados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaAfiliados);
        if (tablaAfiliados.getColumnModel().getColumnCount() > 0) {
            tablaAfiliados.getColumnModel().getColumn(0).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(1).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(2).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(3).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(4).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(5).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 790, 380));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonesCRUD/00-EliminarDesactivado.png"))); // NOI18N
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 144, 55));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonesCRUD/00-EditarDesactivado.png"))); // NOI18N
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 144, 55));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonesCRUD/00-VerDesactivado.png"))); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMouseExited(evt);
            }
        });
        add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 144, 55));

        fondoAfiliados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesPaneles/00-PanelAfiliadosFondo-img.png"))); // NOI18N
        add(fondoAfiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1090, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseEntered
        setBotonActivo("Ver", btnVer);
    }//GEN-LAST:event_btnVerMouseEntered

    private void btnVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseExited
        setBotonInactivo("Ver", btnVer);
    }//GEN-LAST:event_btnVerMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        setBotonActivo("Editar", btnEditar);
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        setBotonInactivo("Editar", btnEditar);
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        setBotonActivo("Eliminar", btnEliminar);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        setBotonInactivo("Eliminar", btnEliminar);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        setBotonActivo("Crear", btnCrear);
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        setBotonInactivo("Crear", btnCrear);
    }//GEN-LAST:event_btnCrearMouseExited

    public JTable getTablaAfiliados() {
        return tablaAfiliados;
    }

    public boolean isBtnVerActivo() {
        return btnVerActivo;
    }

    public boolean isBtnEditarActivo() {
        return btnEditarActivo;
    }

    public boolean isBtnEliminarActivo() {
        return btnEliminarActivo;
    }

    public JLabel getBtnCrear() {
        return btnCrear;
    }

    public JLabel getBtnEditar() {
        return btnEditar;
    }

    public JLabel getBtnEliminar() {
        return btnEliminar;
    }

    public JLabel getBtnVer() {
        return btnVer;
    }
    
    
    
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCrear;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JLabel fondoAfiliados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAfiliados;
    // End of variables declaration//GEN-END:variables
}
